version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - echo Building Lambda function...
      - zip -r search-photos.zip *
  post_build:
    commands:
      - echo Uploading package to S3...
      - aws s3 cp search-photos.zip s3://lambda-build-photo-album/search-photos.zip
      - echo Deploying to Lambda...
      - aws lambda update-function-code --function-name search-photos --s3-bucket lambda-build-photo-album --s3-key search-photos.zip